name: Codecov

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9.5
      - name: Generage coverage report
        run: |
          pip install --upgrade pip
          pip install coverage codecov
          pip install -r requirements.txt
          coverage run manage.py test -v 3
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          env_vars: OS,PYTHON
          name: codecov-pangpangeats
          fail_ci_if_error: true
          verbose: true
